---
- name: user systemd daemon-reload
  become: true
  become_user: '{{ service_user }}'
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ service_user_uid }}"