---
- name: Make install directory
  ansible.builtin.file:
    path: '{{ fedifetcher_root }}'
    owner: '{{ service_user }}'
    group: '{{ service_user }}'
    mode: 0755
    state: directory

- name: Make config directory
  ansible.builtin.file:
    path: '{{ service_user_config }}/FediFetcher'
    owner: '{{ service_user }}'
    group: '{{ service_user }}'
    mode: 0755
    state: directory

- name: Write out config file
  ansible.builtin.template:
    src: config.json.j2
    dest: '{{ service_user_config }}/FediFetcher/config.json'
    owner: '{{ service_user }}'
    group: '{{ service_user }}'

- name: Check if already installed
  ansible.builtin.stat:
    path: '{{ fedifetcher_root }}/install_done'
  register: ff_stat_result

- name: Download and install if not present
  when: not ff_stat_result.stat.exists
  ansible.builtin.include_tasks: install.yml

- name: Set up cron job
  ansible.builtin.cron:
    user: '{{ service_user }}'
    name: FediFetcher
    minute: "15"
    job: 'cd {{ fedifetcher_root }} && {{ fedifetcher_root }}/.venv/bin/python {{ fedifetcher_root }}/find_posts.py -c {{ service_user_config }}/FediFetcher/config.json >> {{ service_user_home }}/log/FediFetcher.log 2>&1'

- name: Set up logrotate
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/FediFetcher
