---
- name: Download and unpack binary
  ansible.builtin.unarchive:
    remote_src: yes
    src: "{{ getmoarfediverse_dl_url }}"
    dest: "{{ getmoarfediverse_root }}"
    keep_newer: yes
    extra_opts:
    - --strip=1

- name: Reset permissions
  ansible.builtin.file:
    path: "{{ getmoarfediverse_root }}"
    owner: '{{ service_user }}'
    group: '{{ service_user }}'
    recurse: yes
