---
- name: Make install directory
  ansible.builtin.file:
    path: '{{ getmoarfediverse_root }}'
    owner: '{{ service_user }}'
    group: '{{ service_user }}'
    mode: 0755
    state: directory

- name: Make config directory
  ansible.builtin.file:
    path: '{{ service_user_config }}/GetMoarFediverse'
    owner: '{{ service_user }}'
    group: '{{ service_user }}'
    mode: 0755
    state: directory

- name: Check if binary is present
  ansible.builtin.stat:
    path: '{{ getmoarfediverse_root }}/GetMoarFediverse'
  register: gmf_stat_result

- name: Download and install if not present
  when: not gmf_stat_result.stat.exists
  ansible.builtin.include_tasks: install.yml

- name: Write out config file
  ansible.builtin.template:
    src: config.json.j2
    dest: '{{ service_user_config }}/GetMoarFediverse/config.json'
    owner: '{{ service_user }}'
    group: '{{ service_user }}'

- name: Set up cron job
  ansible.builtin.cron:
    user: '{{ service_user }}'
    name: GetMoarFediverse
    minute: "5"
    job: '{{ getmoarfediverse_root }}/GetMoarFediverse {{ service_user_config }}/GetMoarFediverse/config.json >> {{ service_user_home }}/log/GetMoarFediverse.log 2>&1'

- name: Set up logrotate
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/GetMoarFediverse
