---
- name: Make install directory
  ansible.builtin.file:
    path: '{{ feed2toot_root }}'
    owner: '{{ service_user }}'
    group: '{{ service_user }}'
    mode: 0755
    state: directory

- name: Make config directory
  ansible.builtin.file:
    path: '{{ service_user_config }}/feed2toot'
    owner: '{{ service_user }}'
    group: '{{ service_user }}'
    mode: 0755
    state: directory

- name: Write out feed2toot config files
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '{{ service_user_config }}/feed2toot/{{ item }}'
    owner: '{{ service_user }}'
    group: '{{ service_user }}'
  loop:
    - feed2toot.ini
    - feed2toot_usercred.txt
    - feed2toot_clientcred.txt

- name: Write out feed2toot static lists
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ service_user_config }}/feed2toot/{{ item }}'
    owner: '{{ service_user }}'
    group: '{{ service_user }}'
  loop:
    - hashtags.txt
    - rsslist.txt

- name: Check if already installed
  ansible.builtin.stat:
    path: '{{ feed2toot_root }}/install_done'
  register: f2t_stat_result

- name: Download and install if not present
  when: not f2t_stat_result.stat.exists
  ansible.builtin.include_tasks: install.yml

- name: Set up cron job
  ansible.builtin.cron:
    user: '{{ service_user }}'
    name: feed2toot
    minute: "34"
    job: 'cd {{ feed2toot_root }} && {{ feed2toot_root }}/.venv/bin/feed2toot --debug -c {{ service_user_config }}/feed2toot/feed2toot.ini >> {{ service_user_home }}/log/feed2toot.log 2>&1'

- name: Set up logrotate
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/feed2toot
